repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: ^src/template_server/models/alembic/versions
        args: ["-l", "100", "--target-version=py310"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8  # C90,E,F,W
        exclude: ^src/template_server/models/alembic
        additional_dependencies:
          - darglint==1.8.1  # DAR
          - flake8-annotations==2.7.0  # ANN
          - flake8-bugbear==22.1.11  # B,B9
          - flake8-cognitive-complexity==0.1.0  # CCR
          - flake8-comprehensions==3.8.0  # C4
          - flake8-docstrings==1.6.0  # D
          - flake8-eradicate==1.2.0  # E800
          - flake8-import-order==0.18.1  # I
          - flake8-polyfill==1.0.2
          - flake8-pytest-style==1.6.0  # PT
          - pep8-naming==0.12.1  # N8
  - repo: local
    hooks:
    -   id: poetry_lock_check
        name: Check if poetry lock file is updated
        entry: |
          python -c "
          from poetry.factory import Factory
          l = Factory().create_poetry('.').locker
          if l.is_locked() and l.is_fresh():
            exit(0)
          else:
            print('run `poetry update` to fix')
            exit(1)
          "
        language: python_venv
        additional_dependencies:
          - poetry
        verbose: True
        files: pyproject.toml
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'
          - '@commitlint/ensure'
          - 'commitlint-plugin-function-rules'
